# Generated by Django 4.0.4 on 2022-05-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_alter_articles_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
