# Generated by Django 4.0.4 on 2022-05-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_class_name_slug_student_number_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_name',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
