# Generated by Django 4.0.4 on 2022-05-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
