# Generated by Django 4.0.4 on 2022-05-31 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jozve', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zojve',
            new_name='Jozve',
        ),
    ]
